import style from "./index.module.css";
import movies from "@/mock/movies.json";
import SearchableLayout from "@/components/searchable-layout";
import Head from "next/head";
import { ReactNode } from "react";
import MovieItem from "@/components/movie-item";

export default function Home() {
  return (
    <>
      <Head>
        <title>onebite cinema</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={style.container}>
        <section className={style.recommend_section}>
          <h3>지금 가장 추천하는 영화</h3>
          <li>
            {movies.slice(0, 3).map((movie) => (
              <MovieItem key={movie.id} {...movie} />
            ))}
          </li>
        </section>
        <section className={style.all_section}>
          <h3>등록된 모든 영화</h3>
          <li>
            {movies.map((movie) => (
              <MovieItem key={movie.id} {...movie} />
            ))}
          </li>
        </section>
      </div>
    </>
  );
}

Home.getLayout = (page: ReactNode) => {
  return <SearchableLayout>{page}</SearchableLayout>;
};
