import style from "./index.module.css";
import SearchableLayout from "@/components/searchable-layout";
import Head from "next/head";
import { ReactNode } from "react";
import MovieItem from "@/components/movie-item";
import { InferGetServerSidePropsType } from "next";
import fetchMovies from "@/lib/fetch-movies";
import fetchRandomMoives from "@/lib/fetch-random-movies";

// SSR, 병렬로 데이터 가져오기
export const getServerSideProps = async () => {
  const [allMovies, recommendMovies] = await Promise.all([
    fetchMovies(),
    fetchRandomMoives(),
  ]);

  return {
    props: { allMovies, recommendMovies },
  };
};

export default function Home({
  allMovies,
  recommendMovies,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>onebite cinema</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={style.container}>
        <section className={style.recommend_section}>
          <h3>지금 가장 추천하는 영화</h3>
          <li>
            {recommendMovies.slice(0, 3).map((movie) => (
              <MovieItem key={movie.id} {...movie} />
            ))}
          </li>
        </section>
        <section className={style.all_section}>
          <h3>등록된 모든 영화</h3>
          <li>
            {allMovies.map((movie) => (
              <MovieItem key={movie.id} {...movie} />
            ))}
          </li>
        </section>
      </div>
    </>
  );
}

Home.getLayout = (page: ReactNode) => {
  return <SearchableLayout>{page}</SearchableLayout>;
};
